import { useState } from 'react';
import {
  FileText,
  Download,
  Plus,
  Calendar,
  User,
  X,
  Mail,
  Printer,
  ShieldCheck,
  MapPin,
  Clock,
  Menu,
  FileCode,
  Map as MapIcon,
  Eye,
  CheckCircle2,
  XCircle,
  AlertTriangle
} from 'lucide-react';
import { getStoredReports, createNewReport, getStoredCases } from '../utils/casesManager';
import { getStoredEmails, getEmailById } from '../utils/emailAnalyzer';
import { StatusBadge } from '../components/common/Badge';
import { formatDateTime } from '../utils/helpers';

export default function Reports() {
  const [reportsList, setReportsList] = useState(() => getStoredReports());
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [previewReport, setPreviewReport] = useState(null);

  const storedCases = getStoredCases();
  const storedEmails = getStoredEmails();

  // Form State
  const [title, setTitle] = useState('');
  const [selectedCase, setSelectedCase] = useState(storedCases[0]?.id || '1024');
  const [selectedEmail, setSelectedEmail] = useState(storedEmails[0]?.id || 'eml-001');
  const [author, setAuthor] = useState('A. Mercer');
  const [format, setFormat] = useState('PDF');
  const [sections, setSections] = useState([
    'Email Header Forensics',
    'SPF/DKIM/DMARC Authentication',
    'Originating IP Geolocation',
    'Domain Intelligence',
    'Threat Actor Correlation',
    'Evidence Chain of Custody'
  ]);

  const handleGenerate = (e) => {
    e.preventDefault();
    const caseObj = storedCases.find(c => c.id === selectedCase) || storedCases[0];
    const reportTitle = title.trim() || `Forensic Report: CASE-2026-${caseObj?.id?.replace('case-', '') || '892'}`;

    createNewReport({
      title: reportTitle,
      caseId: selectedCase,
      targetEmailId: selectedEmail,
      generatedBy: author,
      format: format,
      sections: sections,
    });

    const updated = getStoredReports();
    setReportsList(updated);
    setShowGenerateModal(false);
    setTitle('');
  };

  const handleExportJSON = (report) => {
    const targetEmail = getEmailById(report.targetEmailId || 'eml-001');
    const exportPayload = {
      reportId: report.id,
      title: report.title,
      caseId: report.caseId,
      generatedDate: report.generatedDate,
      generatedBy: report.generatedBy,
      complianceStandard: 'NIST SP 800-86 Forensic Guide',
      forensicFindings: {
        emailSubject: targetEmail?.subject,
        sender: targetEmail?.sender,
        threatScore: targetEmail?.threatScore,
        classification: targetEmail?.classification,
        authentication: targetEmail?.authentication,
        originIP: targetEmail?.originIP,
        receivedHops: targetEmail?.receivedChain,
        indicators: targetEmail?.indicators,
      },
      includedSections: report.sections,
    };

    const blob = new Blob([JSON.stringify(exportPayload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.id}_forensic_report.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportCSV = (report) => {
    const targetEmail = getEmailById(report.targetEmailId || 'eml-001');
    const rows = [
      ['Report ID', report.id],
      ['Title', report.title],
      ['Case ID', report.caseId],
      ['Generated Date', report.generatedDate],
      ['Generated By', report.generatedBy],
      ['Target Subject', targetEmail?.subject || 'Urgent: Invoice OVERDUE - Action Required'],
      ['Sender Address', targetEmail?.sender || 'billing@trusted-vendor.com'],
      ['Threat Score', `${targetEmail?.threatScore || 94}/100`],
      ['Classification', targetEmail?.classification || 'PHISHING'],
      ['Origin IP', targetEmail?.originIP || '185.17.20.19'],
      ['SPF Status', targetEmail?.authentication?.spf?.status || 'FAIL'],
      ['DKIM Status', targetEmail?.authentication?.dkim?.status || 'FAIL'],
      ['DMARC Status', targetEmail?.authentication?.dmarc?.status || 'FAIL'],
      ['', ''],
      ['Detected Threat Indicators', 'Details'],
      ...(targetEmail?.indicators || []).map(ind => [ind.label, ind.detail.replace(/,/g, ';')]),
    ];

    const csvContent = 'data:text/csv;charset=utf-8,' + rows.map(e => e.map(item => `"${item}"`).join(',')).join('\n');
    const encodedUri = encodeURI(csvContent);
    const a = document.createElement('a');
    a.href = encodedUri;
    a.download = `${report.id}_forensics.csv`;
    a.click();
  };

  const handlePrintPDF = (report) => {
    const targetEmail = getEmailById(report.targetEmailId || 'eml-001');
    const printWindow = window.open('', '_blank', 'width=900,height=800');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${report.title}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #111; line-height: 1.6; }
            .header { border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 25px; }
            .badge { display: inline-block; padding: 4px 8px; font-weight: bold; font-size: 12px; background: #fee2e2; color: #b91c1c; border-radius: 4px; }
            .meta-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin-bottom: 25px; font-size: 13px; }
            .section-title { font-size: 16px; font-weight: bold; border-bottom: 1px solid #ddd; padding-bottom: 6px; margin-top: 25px; margin-bottom: 12px; text-transform: uppercase; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 12px; }
            th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
            th { background-color: #f3f4f6; }
            .code-block { font-family: monospace; background: #f9fafb; padding: 12px; border: 1px solid #e5e7eb; border-radius: 4px; font-size: 11px; white-space: pre-wrap; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>THREATTRACE FORENSIC INTELLIGENCE REPORT</h2>
            <p style="margin: 0; color: #666; font-size: 13px;">Confidential Security Incident Investigation · NIST SP 800-86 Format</p>
          </div>

          <div class="meta-grid">
            <div><strong>Report Reference:</strong> ${report.title}</div>
            <div><strong>Case Reference:</strong> ${report.caseId}</div>
            <div><strong>Date Generated:</strong> ${formatDateTime(report.generatedDate)}</div>
            <div><strong>Lead Investigator:</strong> ${report.generatedBy}</div>
          </div>

          <div class="section-title">1. Target Incident Summary</div>
          <table>
            <tr><th>Email Subject</th><td>${targetEmail?.subject || 'Urgent: Invoice OVERDUE - Action Required'}</td></tr>
            <tr><th>Sender (From)</th><td>${targetEmail?.sender || 'billing@trusted-vendor.com'}</td></tr>
            <tr><th>Threat Score</th><td><strong>${targetEmail?.threatScore || 94} / 100</strong> (${targetEmail?.classification || 'PHISHING'})</td></tr>
            <tr><th>Originating Server IP</th><td>${targetEmail?.originIP || '185.17.20.19'} (Amsterdam, Netherlands)</td></tr>
            <tr><th>Authentication</th><td>SPF: FAIL | DKIM: FAIL | DMARC: FAIL (p=reject)</td></tr>
          </table>

          <div class="section-title">2. Detected Indicators of Compromise (IOCs)</div>
          <table>
            <thead>
              <tr><th>Indicator Category</th><th>Forensic Analysis & Verification</th></tr>
            </thead>
            <tbody>
              ${(targetEmail?.indicators || []).map(ind => `
                <tr>
                  <td><strong>${ind.label}</strong></td>
                  <td>${ind.detail}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="section-title">3. Multi-Hop Transmission Trace</div>
          <table>
            <thead>
              <tr><th>Hop</th><th>From Host</th><th>By Gateway</th><th>Relay IP</th><th>Anomaly</th></tr>
            </thead>
            <tbody>
              ${(targetEmail?.receivedChain || []).map(h => `
                <tr>
                  <td>${h.hop}</td>
                  <td>${h.from}</td>
                  <td>${h.by}</td>
                  <td><code>${h.ip}</code></td>
                  <td>${h.anomaly || 'Verified Relay Node'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="section-title">4. Chain of Custody & Evidence Hash</div>
          <p style="font-size: 12px;">Cryptographic integrity verification for email raw source file:</p>
          <div class="code-block">SHA-256: a7f3b2c1d4e5f6a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2 (Preserved in Evidence Locker)</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 400);
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-10">
      {/* 1. Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-[var(--color-text-primary)]">
            Forensic Reports
          </h1>
          <p className="text-sm text-[var(--color-text-muted)] mt-1">
            Generate, manage, and export structured forensic reports (PDF, JSON, CSV)
          </p>
        </div>
        <button
          onClick={() => setShowGenerateModal(true)}
          className="flex items-center gap-1.5 px-4 py-2 text-xs font-bold text-white bg-[var(--color-brand-black)] rounded-[var(--radius-sm)] hover:bg-neutral-800 transition-colors shadow-[var(--shadow-sm)] cursor-pointer self-start sm:self-auto"
        >
          <Plus className="w-3.5 h-3.5 stroke-[2.5]" />
          <span>Generate Report</span>
        </button>
      </div>

      {/* 2. Reports List */}
      <div className="space-y-3">
        {reportsList.map((report) => (
          <div
            key={report.id}
            className="bg-[var(--color-canvas)] border border-[var(--color-border-subtle)] rounded-[var(--radius-md)] p-5 hover:border-[var(--color-border-strong)] transition-all shadow-[var(--shadow-sm)]"
          >
            <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 bg-[var(--color-surface-elevated)] rounded-[var(--radius-sm)] flex items-center justify-center shrink-0">
                  <FileText className="w-5 h-5 text-[var(--color-text-muted)]" />
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-[var(--color-text-primary)]">{report.title}</h3>
                  <div className="flex items-center gap-3 mt-1.5 text-xs text-[var(--color-text-muted)] flex-wrap">
                    <span className="flex items-center gap-1"><Calendar className="w-3 h-3" />{formatDateTime(report.generatedDate)}</span>
                    <span className="flex items-center gap-1"><User className="w-3 h-3" />{report.generatedBy}</span>
                    <span className="font-mono">{report.caseId}</span>
                    <StatusBadge status={report.status} />
                  </div>
                  <div className="flex flex-wrap gap-1.5 mt-2.5">
                    {report.sections.map((section) => (
                      <span key={section} className="px-2 py-0.5 text-[10px] bg-[var(--color-surface)] border border-[var(--color-border-subtle)] rounded text-[var(--color-text-muted)]">
                        {section}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Export Actions */}
              <div className="flex items-center gap-1.5 shrink-0 self-end md:self-center">
                <button
                  onClick={() => setPreviewReport(report)}
                  className="flex items-center gap-1 px-3 py-1.5 text-xs font-semibold bg-[var(--color-surface)] border border-[var(--color-border-subtle)] rounded-[var(--radius-sm)] hover:border-[var(--color-border-strong)] transition-colors cursor-pointer text-[var(--color-text-primary)]"
                >
                  <Eye className="w-3.5 h-3.5 text-slate-500" />
                  <span>Preview</span>
                </button>
                <button
                  onClick={() => handlePrintPDF(report)}
                  className="flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-white bg-[var(--color-brand-black)] rounded-[var(--radius-sm)] hover:bg-neutral-800 transition-colors shadow-[var(--shadow-sm)] cursor-pointer"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <span>Print / PDF</span>
                </button>
                <button
                  onClick={() => handleExportJSON(report)}
                  className="flex items-center gap-1 px-2.5 py-1.5 text-xs font-mono font-semibold bg-[var(--color-surface)] border border-[var(--color-border-subtle)] rounded-[var(--radius-sm)] hover:border-[var(--color-border-strong)] transition-colors cursor-pointer"
                >
                  <Download className="w-3 h-3" />
                  <span>JSON</span>
                </button>
                <button
                  onClick={() => handleExportCSV(report)}
                  className="flex items-center gap-1 px-2.5 py-1.5 text-xs font-mono font-semibold bg-[var(--color-surface)] border border-[var(--color-border-subtle)] rounded-[var(--radius-sm)] hover:border-[var(--color-border-strong)] transition-colors cursor-pointer"
                >
                  <Download className="w-3 h-3" />
                  <span>CSV</span>
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* 3. Generate Report Modal */}
      {showGenerateModal && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <div className="bg-[var(--color-canvas)] border border-[var(--color-border-subtle)] rounded-[var(--radius-md)] max-w-lg w-full max-h-[90vh] overflow-y-auto p-6 shadow-xl animate-in fade-in zoom-in duration-200">
            <div className="flex items-center justify-between pb-3 border-b border-[var(--color-border-subtle)] mb-4">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-[var(--color-brand-black)]" />
                <h2 className="text-base font-bold text-[var(--color-text-primary)]">Generate Forensic Report</h2>
              </div>
              <button onClick={() => setShowGenerateModal(false)} className="text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)] cursor-pointer">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleGenerate} className="space-y-4 text-xs">
              <div>
                <label className="block font-semibold text-[var(--color-text-primary)] mb-1">Report Title</label>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g. Forensic Report: CASE-2023-892"
                  className="w-full px-3 py-2 border border-[var(--color-border-subtle)] rounded-[var(--radius-sm)] bg-[var(--color-surface)] text-[var(--color-text-primary)] focus:outline-none focus:ring-1 focus:ring-[var(--color-brand-black)] text-xs"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-semibold text-[var(--color-text-primary)] mb-1">Target Case</label>
                  <select
                    value={selectedCase}
                    onChange={(e) => setSelectedCase(e.target.value)}
                    className="w-full px-3 py-2 border border-[var(--color-border-subtle)] rounded-[var(--radius-sm)] bg-[var(--color-surface)] text-[var(--color-text-primary)] focus:outline-none focus:ring-1 focus:ring-[var(--color-brand-black)] text-xs font-mono"
                  >
                    {storedCases.map(c => (
                      <option key={c.id} value={c.id}>[{c.id}] {c.title?.substring(0, 30)}...</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block font-semibold text-[var(--color-text-primary)] mb-1">Target Scanned Email</label>
                  <select
                    value={selectedEmail}
                    onChange={(e) => setSelectedEmail(e.target.value)}
                    className="w-full px-3 py-2 border border-[var(--color-border-subtle)] rounded-[var(--radius-sm)] bg-[var(--color-surface)] text-[var(--color-text-primary)] focus:outline-none focus:ring-1 focus:ring-[var(--color-brand-black)] text-xs font-mono"
                  >
                    {storedEmails.map(em => (
                      <option key={em.id} value={em.id}>[{em.id}] {em.subject?.substring(0, 30)}...</option>
                    ))}
                  </select>
                </div>
              </div>

              <div>
                <label className="block font-semibold text-[var(--color-text-primary)] mb-1">Lead Investigator</label>
                <input
                  type="text"
                  value={author}
                  onChange={(e) => setAuthor(e.target.value)}
                  className="w-full px-3 py-2 border border-[var(--color-border-subtle)] rounded-[var(--radius-sm)] bg-[var(--color-surface)] text-[var(--color-text-primary)] focus:outline-none focus:ring-1 focus:ring-[var(--color-brand-black)] text-xs"
                />
              </div>

              <div>
                <label className="block font-semibold text-[var(--color-text-primary)] mb-2">Sections to Include in Forensic Dossier</label>
                <div className="grid grid-cols-2 gap-2 text-xs">
                  {[
                    'Email Header Forensics',
                    'SPF/DKIM/DMARC Authentication',
                    'Originating IP Geolocation',
                    'Domain Intelligence',
                    'Threat Actor Correlation',
                    'Evidence Chain of Custody'
                  ].map((sec) => (
                    <label key={sec} className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={sections.includes(sec)}
                        onChange={(e) => {
                          if (e.target.checked) setSections([...sections, sec]);
                          else setSections(sections.filter(s => s !== sec));
                        }}
                        className="rounded accent-[var(--color-brand-black)]"
                      />
                      <span className="text-[var(--color-text-secondary)]">{sec}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div className="flex items-center justify-end gap-2 pt-3 border-t border-[var(--color-border-subtle)]">
                <button
                  type="button"
                  onClick={() => setShowGenerateModal(false)}
                  className="px-4 py-2 border border-[var(--color-border-subtle)] rounded-[var(--radius-sm)] hover:bg-[var(--color-surface)] transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 font-semibold text-white bg-[var(--color-brand-black)] rounded-[var(--radius-sm)] hover:bg-neutral-800 transition-colors cursor-pointer"
                >
                  Generate Forensic Dossier
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* 4. Forensic Report Preview Modal (Exact Recreation of Reference Screenshot) */}
      {previewReport && (() => {
        const targetEmail = getEmailById(previewReport.targetEmailId || 'eml-001');
        const caseNum = previewReport.caseId ? previewReport.caseId.replace('case-', '') : '2023-892';
        const reportTitle = previewReport.title.includes('CASE-') ? previewReport.title : `Forensic Report: CASE-${caseNum.length === 4 ? `2026-${caseNum}` : caseNum}`;

        return (
          <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
            <div className="bg-[#FAFAFA] border border-[var(--color-border-subtle)] rounded-lg max-w-4xl w-full my-auto max-h-[95vh] overflow-y-auto p-6 sm:p-8 shadow-2xl space-y-6">
              {/* Modal Top Bar */}
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-4 border-b border-slate-200">
                <div>
                  <div className="flex items-center gap-2">
                    <h2 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900">
                      {reportTitle}
                    </h2>
                  </div>
                  <p className="text-xs text-slate-500 mt-1">
                    Generated: Oct 24, 2026 14:32 UTC | Analyst: {previewReport.generatedBy || 'A. Mercer'}
                  </p>
                </div>

                {/* Top Action Buttons */}
                <div className="flex items-center gap-2 self-start sm:self-auto">
                  <button
                    onClick={() => alert(`Forensic report dispatch queued for SOC Incident Response Team (${previewReport.generatedBy}).`)}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-white border border-slate-300 rounded shadow-xs hover:border-slate-400 transition-colors cursor-pointer text-slate-700"
                  >
                    <Mail className="w-3.5 h-3.5 text-slate-500" />
                    <span>Email to SOC</span>
                  </button>

                  <button
                    onClick={() => handleExportCSV(previewReport)}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-white border border-slate-300 rounded shadow-xs hover:border-slate-400 transition-colors cursor-pointer text-slate-700"
                  >
                    <Download className="w-3.5 h-3.5 text-slate-500" />
                    <span>Export CSV</span>
                  </button>

                  <button
                    onClick={() => handlePrintPDF(previewReport)}
                    className="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-bold text-white bg-black rounded shadow-xs hover:bg-neutral-800 transition-colors cursor-pointer"
                  >
                    <FileText className="w-3.5 h-3.5" />
                    <span>Generate PDF</span>
                  </button>

                  <button
                    onClick={() => setPreviewReport(null)}
                    className="p-1.5 text-slate-400 hover:text-slate-800 hover:bg-slate-200 rounded transition-colors ml-1 cursor-pointer"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>
              </div>

              {/* Row 1: Threat Score (Left ~30%) & Case Summary (Right ~70%) */}
              <div className="grid grid-cols-1 md:grid-cols-12 gap-5 items-stretch">
                {/* Threat Score Card */}
                <div className="md:col-span-4 bg-white border border-slate-200 border-t-4 border-t-[#B91C1C] rounded p-6 shadow-xs flex flex-col items-center justify-center text-center">
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                    Threat Score
                  </span>
                  <p className="text-5xl sm:text-6xl font-extrabold text-[#B91C1C] tracking-tight font-sans">
                    {targetEmail?.threatScore || 94}
                  </p>
                  <div className="mt-3">
                    <span className="px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider rounded-full bg-red-100 text-red-700">
                      CRITICAL SEVERITY
                    </span>
                  </div>
                </div>

                {/* Case Summary Card */}
                <div className="md:col-span-8 bg-white border border-slate-200 rounded p-6 shadow-xs flex flex-col justify-between">
                  <div className="flex items-center gap-2 pb-3 border-b border-slate-100 mb-4">
                    <Menu className="w-4 h-4 text-slate-800" />
                    <h3 className="text-sm font-bold text-slate-900">Case Summary</h3>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-y-4 gap-x-6 text-xs">
                    <div>
                      <span className="text-slate-400 text-[11px] block mb-0.5">Target Subject</span>
                      <span className="font-semibold text-slate-900">
                        "{targetEmail?.subject || 'Urgent: Invoice OVERDUE - Action Required'}"
                      </span>
                    </div>

                    <div>
                      <span className="text-slate-400 text-[11px] block mb-0.5">Sender Address (Spoofed)</span>
                      <span className="font-mono text-slate-900 font-medium">
                        {targetEmail?.sender || 'billing@trusted-vendor.com'}
                      </span>
                    </div>

                    <div>
                      <span className="text-slate-400 text-[11px] block mb-0.5">Return-Path</span>
                      <span className="font-mono text-red-600 font-medium">
                        bounces@{targetEmail?.sender?.split('@')[1] || 'malicious-domain.su'}
                      </span>
                    </div>

                    <div>
                      <span className="text-slate-400 text-[11px] block mb-0.5">Message-ID</span>
                      <span className="font-mono text-slate-600 truncate block">
                        &lt;202610241422.x9EE..&gt;
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Row 2: Authentication Results (Left ~50%) & Origin Analysis (Right ~50%) */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                {/* Authentication Results */}
                <div className="bg-white border border-slate-200 rounded p-6 shadow-xs space-y-4">
                  <div className="flex items-center gap-2 mb-2">
                    <ShieldCheck className="w-4 h-4 text-slate-800" />
                    <h3 className="text-sm font-bold text-slate-900">Authentication Results</h3>
                  </div>

                  <div className="space-y-2.5 text-xs">
                    <div className="flex items-center justify-between p-2.5 bg-red-50/70 border border-red-100 rounded">
                      <span className="font-medium text-slate-800">SPF (Sender Policy Framework)</span>
                      <span className="px-2.5 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-700">
                        FAIL
                      </span>
                    </div>

                    <div className="flex items-center justify-between p-2.5 bg-red-50/70 border border-red-100 rounded">
                      <span className="font-medium text-slate-800">DKIM (DomainKeys Identified Mail)</span>
                      <span className="px-2.5 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-700">
                        FAIL
                      </span>
                    </div>

                    <div className="flex items-center justify-between p-2.5 bg-red-50/70 border border-red-100 rounded">
                      <span className="font-medium text-slate-800">DMARC</span>
                      <span className="px-2.5 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-700">
                        FAIL (p=reject)
                      </span>
                    </div>
                  </div>
                </div>

                {/* Origin Analysis */}
                <div className="bg-white border border-slate-200 rounded p-6 shadow-xs space-y-4">
                  <div className="flex items-center gap-2 mb-2">
                    <MapPin className="w-4 h-4 text-slate-800" />
                    <h3 className="text-sm font-bold text-slate-900">Origin Analysis</h3>
                  </div>

                  <div className="grid grid-cols-3 gap-2 text-xs">
                    <div>
                      <span className="text-slate-400 text-[10px] uppercase font-bold block mb-0.5">Originating IP</span>
                      <span className="font-mono font-bold text-red-600">
                        {targetEmail?.originIP || '185.17.20.19'}
                      </span>
                    </div>

                    <div>
                      <span className="text-slate-400 text-[10px] uppercase font-bold block mb-0.5">Geolocation</span>
                      <span className="font-medium text-slate-800">
                        {targetEmail?.originCountry === 'Germany' ? 'Frankfurt, Germany' : 'Amsterdam, Netherlands'}
                      </span>
                    </div>

                    <div>
                      <span className="text-slate-400 text-[10px] uppercase font-bold block mb-0.5">ASN</span>
                      <span className="font-mono text-slate-800 font-semibold">
                        AS398324
                      </span>
                    </div>
                  </div>

                  {/* Clean Map Placeholder Graphic */}
                  <div className="w-full h-24 bg-slate-100 rounded border border-slate-200 flex items-center justify-center">
                    <MapIcon className="w-8 h-8 text-slate-400 stroke-[1.5]" />
                  </div>
                </div>
              </div>

              {/* Row 3: Evidence Log & Timeline (Full Width) */}
              <div className="bg-white border border-slate-200 rounded p-6 shadow-xs space-y-4">
                <div className="flex items-center gap-2 mb-2">
                  <Clock className="w-4 h-4 text-slate-800" />
                  <h3 className="text-sm font-bold text-slate-900">Evidence Log & Timeline</h3>
                </div>

                <div className="space-y-4 text-xs pl-2">
                  {/* Item 1 */}
                  <div className="relative pl-6 border-l-2 border-slate-200 pb-2">
                    <div className="absolute -left-[5px] top-0 w-2.5 h-2.5 rounded-full bg-slate-900" />
                    <span className="text-[11px] font-mono text-slate-400 block mb-0.5">14:22:01 UTC</span>
                    <p className="font-bold text-slate-800 mb-1.5">Email received at edge MTA.</p>
                    <div className="p-2.5 bg-slate-100 rounded border border-slate-200 font-mono text-[11px] text-slate-600">
                      Received: from mail.{targetEmail?.sender?.split('@')[1] || 'malicious-domain.su'} ({targetEmail?.originIP || '185.17.20.19'}) by edge.corp.local...
                    </div>
                  </div>

                  {/* Item 2 */}
                  <div className="relative pl-6 border-l-2 border-slate-200 pb-2">
                    <div className="absolute -left-[5px] top-0 w-2.5 h-2.5 rounded-full bg-red-600" />
                    <span className="text-[11px] font-mono text-slate-400 block mb-0.5">14:22:05 UTC</span>
                    <p className="font-bold text-slate-800 mb-1.5">Authentication checks failed. Policy enforcement triggered.</p>
                    <div className="p-2.5 bg-slate-100 rounded border border-slate-200 font-mono text-[11px] text-slate-600">
                      Authentication-Results: spf=fail (sender IP is {targetEmail?.originIP || '185.17.20.19'})...
                    </div>
                  </div>

                  {/* Item 3 */}
                  <div className="relative pl-6 pb-1">
                    <div className="absolute -left-[5px] top-0 w-2.5 h-2.5 rounded-full bg-slate-400" />
                    <span className="text-[11px] font-mono text-slate-400 block mb-0.5">14:22:12 UTC</span>
                    <p className="font-bold text-slate-800">Payload extracted and sent to sandbox analysis.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );
      })()}
    </div>
  );
}
